import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readInstallationToken } from './src/pairing.mjs';
import { prepareLocalPlugin } from './scripts/local-plugin.mjs';
import { packageSkill } from './scripts/package-skill.mjs';
process.chdir(dirname(fileURLToPath(import.meta.url)));
await build({
  entryPoints: ['plugin/code.ts'], bundle: true, outfile: 'plugin/code.js',
  target: 'es2017', format: 'iife', legalComments: 'none',
});
await mkdir('runtime', { recursive: true });
const result = await build({
  entryPoints: ['src/server.mjs'], bundle: true, outfile: 'runtime/server.mjs',
  platform: 'node', target: 'node22', format: 'esm', metafile: true,
  banner: { js: "import { createRequire as __createRequire } from 'node:module'; const require = __createRequire(import.meta.url);" },
  external: ['bufferutil', 'utf-8-validate'], legalComments: 'eof',
});
// Preserve licenses of packages that actually contribute code to the bundle.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.includes('node_modules/')) continue;
  let directory = dirname(resolve(input));
  while (directory !== dirname(directory)) {
    try {
      const pkg = JSON.parse(await readFile(resolve(directory, 'package.json'), 'utf8'));
      if (pkg.name) { packages.set(directory, pkg); break; }
    } catch {}
    directory = dirname(directory);
  }
}
let notices = '# Bundled third-party software\n\nGenerated by build.mjs from the server bundle dependency graph.\n';
for (const [directory, pkg] of [...packages].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
  let licenseText = '';
  for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENSE-MIT', 'license', 'license.md', 'License']) {
    try { licenseText = await readFile(resolve(directory, name), 'utf8'); break; } catch {}
  }
  if (!licenseText) throw new Error(`Missing bundled dependency license: ${relative(process.cwd(), directory)}`);
  notices += `\n## ${pkg.name} ${pkg.version} (${pkg.license ?? 'see license'})\n\n${licenseText.trim()}\n`;
}
await writeFile('runtime/THIRD_PARTY_NOTICES.md', notices);
if (await readInstallationToken(process.cwd())) await prepareLocalPlugin(process.cwd());
await packageSkill(process.cwd());
